/*
 * Device component template.
 *
 * Copy this file, rename it (e.g. Computer.tsx), fill in the GLB path and
 * node names, and it becomes a new swappable device for the 3D test page.
 *
 * Minimum requirements for a device component:
 *   1. Export a `Model` function component that renders the 3D device.
 *   2. Export a `ControlEvent` interface (or device-specific name) so the
 *      host page can subscribe to clicks/moves.
 *   3. Load your .glb with `useGLTF('/models/yourdevice.glb')`.
 *
 * To swap: change the import line in src/app/3d-test/page.tsx.
 *
 * See SteamDeck.tsx for a full working example with joystick drag, click
 * zones, and real mesh interaction.
 */

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type ThreeElements } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

// ─── Types ───────────────────────────────────────────────────

export type DeviceControl = 'power' | 'screen' | 'none'

export interface DeviceControlEvent {
  type: 'down' | 'up' | 'move'
  mesh: string
  control: DeviceControl
  uv: { u: number; v: number } | null
  value?: { x: number; y: number }
}

// Replace with your .glb's node structure (generated by `gltfjsx`).
type GLTFResult = GLTF & {
  nodes: {
    // e.g.:
    // screen: THREE.Mesh
    // power_button: THREE.Mesh
    // chassis: THREE.Mesh
  }
  materials: {
    // e.g.:
    // ['plastic']: THREE.MeshStandardMaterial
  }
}

type DeviceProps = ThreeElements['group'] & {
  onControlEvent?: (event: DeviceControlEvent) => void
}

// ─── Component ───────────────────────────────────────────────

export function Model({ onControlEvent, ...props }: DeviceProps) {
  const { nodes, materials } = useGLTF('/models/YOUR_DEVICE.glb') as unknown as GLTFResult
  void nodes
  void materials
  void onControlEvent

  return (
    <group {...props} dispose={null}>
      {/* Render your device's meshes here. Example:
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.chassis.geometry} material={materials.plastic} />
        <mesh geometry={nodes.screen.geometry} material={materials.plastic} />
      </group>
      */}
    </group>
  )
}

useGLTF.preload('/models/YOUR_DEVICE.glb')
