/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/steam_deck.glb -o src/components/SteamDeck.tsx -t 
Author: ghostban12 (https://sketchfab.com/ghostban12)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/steam-deck-console-c8f6dc1b46dd40a082bf677822a3b5c9
Title: Steam_deck_console
*/

import * as THREE from 'three'
import React, { useEffect, useRef, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { type ThreeElements, type ThreeEvent, useThree } from '@react-three/fiber'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    body_1: THREE.Mesh
    body_2: THREE.Mesh
    body_3: THREE.Mesh
    button_b: THREE.Mesh
    dpad: THREE.Mesh
    stick_left_base_1: THREE.Mesh
    stick_left_base_2: THREE.Mesh
    stick_left_stem_1: THREE.Mesh
    stick_left_stem_2: THREE.Mesh
    stick_right_base_1: THREE.Mesh
    stick_right_base_2: THREE.Mesh
    stick_right_stem_1: THREE.Mesh
    stick_right_stem_2: THREE.Mesh
    trigger_left_1: THREE.Mesh
    trigger_left_2: THREE.Mesh
    trigger_right_1: THREE.Mesh
    trigger_right_2: THREE.Mesh
  }
  materials: {
    ['steamDeckIMGShiney.png.001']: THREE.MeshStandardMaterial
    ['steamDeckIMG.png.001']: THREE.MeshStandardMaterial
    ['steamDeckIMGEmissive.png.001']: THREE.MeshStandardMaterial
  }
}

export type SteamDeckControl = 'a' | 'b' | 'x' | 'y' | 'dpad' | 'leftStick' | 'rightStick' | 'view' | 'menu' | 'leftBumper' | 'rightBumper' | 'screen' | 'none' | 'probe'

export interface SteamDeckControlEvent {
  type: 'move' | 'down' | 'up'
  mesh: string
  control: SteamDeckControl
  uv: { u: number; v: number } | null
  localPoint?: { x: number; y: number; z: number }
  value?: { x: number; y: number }
  bounds?: string
}

type SteamDeckProps = ThreeElements['group'] & {
  onControlEvent?: (event: SteamDeckControlEvent) => void
}

type ProxyControlProps = {
  onControlEvent?: (event: SteamDeckControlEvent) => void
}

function setPointerCaptureSafely(event: ThreeEvent<PointerEvent>) {
  const target = event.target as EventTarget & {
    setPointerCapture?: (pointerId: number) => void
  }
  target.setPointerCapture?.(event.pointerId)
}

function releasePointerCaptureSafely(event: ThreeEvent<PointerEvent>) {
  const target = event.target as EventTarget & {
    releasePointerCapture?: (pointerId: number) => void
  }
  target.releasePointerCapture?.(event.pointerId)
}

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value))
}

function emitSimpleControl(
  onControlEvent: ProxyControlProps['onControlEvent'],
  control: SteamDeckControl,
  mesh: string,
  type: SteamDeckControlEvent['type']
) {
  onControlEvent?.({
    control,
    mesh,
    type,
    uv: null,
  })
}

function FaceButton({ control, position, onControlEvent }: ProxyControlProps & { control: 'a' | 'b' | 'x' | 'y'; position: [number, number, number] }) {
  const [pressed, setPressed] = useState(false)
  const emit = (type: SteamDeckControlEvent['type']) => emitSimpleControl(onControlEvent, control, `proxy-${control}`, type)

  // Press INTO face = increase Y (same rationale as PressableMesh)
  const y = pressed ? position[1] + 0.03 : position[1]

  return (
    <mesh
      position={[position[0], y, position[2]]}
      onPointerOver={() => { document.body.style.cursor = 'pointer' }}
      onPointerOut={(event) => { releasePointerCaptureSafely(event); document.body.style.cursor = 'auto'; setPressed(false); emit('up') }}
      onPointerDown={(event) => { event.stopPropagation(); setPointerCaptureSafely(event); setPressed(true); emit('down') }}
      onPointerUp={(event) => { event.stopPropagation(); releasePointerCaptureSafely(event); setPressed(false); emit('up') }}
    >
      <cylinderGeometry args={[0.2, 0.2, 0.12, 24]} />
      <meshStandardMaterial
        color={control === 'a' ? '#2a7a2a' : control === 'b' ? '#7a2a2a' : control === 'x' ? '#2a4a7a' : '#7a6a2a'}
        metalness={0.2}
        roughness={0.6}
      />
    </mesh>
  )
}

function DPad({ position, onControlEvent }: ProxyControlProps & { position: [number, number, number] }) {
  const [pressed, setPressed] = useState(false)
  const emit = (type: SteamDeckControlEvent['type']) => emitSimpleControl(onControlEvent, 'dpad', 'proxy-dpad', type)

  return (
    <group position={[position[0], pressed ? position[1] + 0.02 : position[1], position[2]]}>
      <mesh><boxGeometry args={[0.28, 0.06, 0.1]} /><meshStandardMaterial color="#181818" metalness={0.25} roughness={0.78} /></mesh>
      <mesh><boxGeometry args={[0.1, 0.06, 0.28]} /><meshStandardMaterial color="#181818" metalness={0.25} roughness={0.78} /></mesh>
      <mesh
        onPointerOver={() => { document.body.style.cursor = 'pointer' }}
        onPointerOut={(event) => { releasePointerCaptureSafely(event); document.body.style.cursor = 'auto'; setPressed(false); emit('up') }}
        onPointerDown={(event) => { event.stopPropagation(); setPointerCaptureSafely(event); setPressed(true); emit('down') }}
        onPointerUp={(event) => { event.stopPropagation(); releasePointerCaptureSafely(event); setPressed(false); emit('up') }}
      >
        <boxGeometry args={[0.35, 0.03, 0.35]} />
        <meshBasicMaterial transparent opacity={0} />
      </mesh>
    </group>
  )
}

function PillButton({ control, position, size, onControlEvent }: ProxyControlProps & { control: 'view' | 'menu' | 'leftBumper' | 'rightBumper'; position: [number, number, number]; size: [number, number, number] }) {
  const [pressed, setPressed] = useState(false)
  const emit = (type: SteamDeckControlEvent['type']) => emitSimpleControl(onControlEvent, control, `proxy-${control}`, type)

  return (
    <mesh
      position={[position[0], pressed ? position[1] + 0.02 : position[1], position[2]]}
      onPointerOver={() => { document.body.style.cursor = 'pointer' }}
      onPointerOut={(event) => { releasePointerCaptureSafely(event); document.body.style.cursor = 'auto'; setPressed(false); emit('up') }}
      onPointerDown={(event) => { event.stopPropagation(); setPointerCaptureSafely(event); setPressed(true); emit('down') }}
      onPointerUp={(event) => { event.stopPropagation(); releasePointerCaptureSafely(event); setPressed(false); emit('up') }}
    >
      <boxGeometry args={size} />
      <meshStandardMaterial color="#16171a" metalness={0.22} roughness={0.82} />
    </mesh>
  )
}

function ScreenOverlay({ position, size, onControlEvent }: ProxyControlProps & { position: [number, number, number]; size: [number, number] }) {
  const [active, setActive] = useState(false)
  const emit = (type: SteamDeckControlEvent['type']) => emitSimpleControl(onControlEvent, 'screen', 'proxy-screen', type)

  return (
    <group position={position}>
      <mesh
        onPointerOver={() => { document.body.style.cursor = 'pointer' }}
        onPointerOut={(event) => { releasePointerCaptureSafely(event); document.body.style.cursor = 'auto'; setActive(false); emit('up') }}
        onPointerDown={(event) => { event.stopPropagation(); setPointerCaptureSafely(event); setActive(true); emit('down') }}
        onPointerUp={(event) => { event.stopPropagation(); releasePointerCaptureSafely(event); setActive(false); emit('up') }}
      >
        <planeGeometry args={size} />
        <meshBasicMaterial transparent opacity={0.001} side={THREE.DoubleSide} />
      </mesh>
      {active && (
        <mesh position={[0, -0.003, 0]}>
          <planeGeometry args={[size[0] * 0.95, size[1] * 0.95]} />
          <meshBasicMaterial color="#7cff9f" transparent opacity={0.15} side={THREE.DoubleSide} />
        </mesh>
      )}
    </group>
  )
}

interface MeshSlot {
  geometry: THREE.BufferGeometry
  material: THREE.Material
}

interface RealStickProps {
  control: 'leftStick' | 'rightStick'
  /** Meshes that rotate with the stick tilt (stem + cap). */
  tiltMeshes: MeshSlot[]
  /** Meshes pinned to the gamepad body (base ring). */
  fixedMeshes?: MeshSlot[]
  position: [number, number, number]
  onControlEvent?: (event: SteamDeckControlEvent) => void
}

function RealStick({ control, tiltMeshes, fixedMeshes = [], position, onControlEvent }: RealStickProps) {
  const [dragging, setDragging] = useState(false)
  const [vector, setVector] = useState({ x: 0, y: 0 })
  const groupRef = useRef<THREE.Group>(null)
  const { camera, gl } = useThree()
  const onControlEventRef = useRef(onControlEvent)
  useEffect(() => { onControlEventRef.current = onControlEvent }, [onControlEvent])

  const TILT_MAX = 0.25
  const DRAG_RADIUS = 0.3

  // Window-level drag: project mouse ray onto virtual plane at stick position.
  // Capture-phase listeners block OrbitControls during drag.
  useEffect(() => {
    if (!dragging) return
    const domElement = gl.domElement

    const onPointerMove = (e: PointerEvent) => {
      e.stopPropagation()
      if (!groupRef.current) return
      const stickWorld = new THREE.Vector3()
      groupRef.current.getWorldPosition(stickWorld)

      const rect = domElement.getBoundingClientRect()
      const ndc = new THREE.Vector2(
        ((e.clientX - rect.left) / rect.width) * 2 - 1,
        -((e.clientY - rect.top) / rect.height) * 2 + 1
      )
      const ray = new THREE.Raycaster()
      ray.setFromCamera(ndc, camera)

      const camDir = camera.getWorldDirection(new THREE.Vector3())
      const plane = new THREE.Plane().setFromNormalAndCoplanarPoint(camDir.clone().negate(), stickWorld)
      const hit = new THREE.Vector3()
      if (!ray.ray.intersectPlane(plane, hit)) return

      const local = groupRef.current.worldToLocal(hit)
      const next = {
        x: clamp(local.x / DRAG_RADIUS, -1, 1),
        y: clamp(local.z / DRAG_RADIUS, -1, 1),
      }
      setVector(next)
      onControlEventRef.current?.({
        control,
        mesh: control,
        type: 'move',
        uv: null,
        value: next,
      })
    }

    const onPointerUp = (e: PointerEvent) => {
      e.stopPropagation()
      document.body.style.cursor = 'auto'
      setDragging(false)
      setVector({ x: 0, y: 0 })
      onControlEventRef.current?.({
        control,
        mesh: control,
        type: 'up',
        uv: null,
        value: { x: 0, y: 0 },
      })
    }

    domElement.addEventListener('pointermove', onPointerMove, true)
    domElement.addEventListener('pointerup', onPointerUp, true)
    return () => {
      domElement.removeEventListener('pointermove', onPointerMove, true)
      domElement.removeEventListener('pointerup', onPointerUp, true)
    }
  }, [dragging, camera, gl, control])

  // Fixed meshes (base ring) sit at the anchor position but never tilt.
  // Tilt meshes (stem + cap) rotate with the stick vector.
  // groupRef tracks the tilting group so worldToLocal projects correctly.
  return (
    <group position={position}>
      {/* BASE — stays locked to the gamepad body */}
      {fixedMeshes.map((m, i) => (
        <mesh key={`fixed-${i}`} geometry={m.geometry} material={m.material} />
      ))}

      {/* STEM + CAP — tilts with user drag */}
      <group ref={groupRef} rotation={[-vector.y * TILT_MAX, 0, -vector.x * TILT_MAX]}>
        <group
          onPointerOver={() => { document.body.style.cursor = 'grab' }}
          onPointerOut={() => { if (!dragging) document.body.style.cursor = 'auto' }}
          onPointerDown={(event) => {
            event.stopPropagation()
            document.body.style.cursor = 'grabbing'
            setDragging(true)
            onControlEvent?.({
              control,
              mesh: control,
              type: 'down',
              uv: null,
              value: { x: 0, y: 0 },
            })
          }}
        >
          {tiltMeshes.map((m, i) => (
            <mesh key={`tilt-${i}`} geometry={m.geometry} material={m.material} />
          ))}
        </group>
      </group>
    </group>
  )
}

// ─── Simple click zone ───────────────────────────────────────
// Invisible (or colored, if debug) box sitting on top of a real mesh.
// Fires control events on click. Does not animate, does not fight for
// pointer capture with OrbitControls.
interface ClickZoneProps {
  control: SteamDeckControl
  position: [number, number, number]
  size: [number, number, number]
  /** If provided, zone is rendered with this color (for debugging placement).
      Omit for transparent/invisible zone over real geometry. */
  color?: string
  onControlEvent?: (event: SteamDeckControlEvent) => void
}

function ClickZone({ control, position, size, color, onControlEvent }: ClickZoneProps) {
  const [hovered, setHovered] = useState(false)
  const [pressed, setPressed] = useState(false)
  const emit = (type: SteamDeckControlEvent['type']) =>
    emitSimpleControl(onControlEvent, control, `zone-${control}`, type)

  return (
    <mesh
      position={position}
      onPointerOver={(e) => { e.stopPropagation(); setHovered(true); document.body.style.cursor = 'pointer' }}
      onPointerOut={(e) => { e.stopPropagation(); setHovered(false); setPressed(false); document.body.style.cursor = 'auto' }}
      onPointerDown={(e) => { e.stopPropagation(); setPressed(true); emit('down') }}
      onPointerUp={(e) => { e.stopPropagation(); setPressed(false); emit('up') }}
    >
      <boxGeometry args={size} />
      {color ? (
        <meshStandardMaterial
          color={pressed ? '#ffffff' : hovered ? color : color}
          opacity={pressed ? 1 : hovered ? 0.95 : 0.85}
          transparent
          metalness={0.2}
          roughness={0.5}
        />
      ) : (
        <meshBasicMaterial
          transparent
          opacity={hovered ? 0.15 : 0}
          color={pressed ? '#7cff9f' : '#ffffff'}
        />
      )}
    </mesh>
  )
}

// ─── Pressable real-geometry button/trigger ──────────────────
interface PressableMeshProps {
  control: SteamDeckControl
  meshes: MeshSlot[]
  position: [number, number, number]
  /**
   * How far the mesh depresses on click. Increases pre-rotation Y, which after the
   * outer -90°X rotation maps to world -Z (away from camera = pressing INTO the
   * gamepad face since the camera views the face from in front).
   */
  pressDepth?: number
  onControlEvent?: (event: SteamDeckControlEvent) => void
}

function PressableMesh({
  control,
  meshes,
  position,
  pressDepth = 0.04,
  onControlEvent,
}: PressableMeshProps) {
  const [pressed, setPressed] = useState(false)
  const emit = (type: SteamDeckControlEvent['type']) =>
    emitSimpleControl(onControlEvent, control, `real-${control}`, type)

  // Press INTO the gamepad face. After -90°X outer rotation, pre-Y+ => world Z- (away from camera).
  const y = pressed ? position[1] + pressDepth : position[1]

  return (
    <group
      position={[position[0], y, position[2]]}
      onPointerOver={() => { document.body.style.cursor = 'pointer' }}
      onPointerOut={(event) => {
        releasePointerCaptureSafely(event)
        document.body.style.cursor = 'auto'
        if (pressed) { setPressed(false); emit('up') }
      }}
      onPointerDown={(event) => {
        event.stopPropagation()
        setPointerCaptureSafely(event)
        setPressed(true)
        emit('down')
      }}
      onPointerUp={(event) => {
        event.stopPropagation()
        releasePointerCaptureSafely(event)
        setPressed(false)
        emit('up')
      }}
    >
      {meshes.map((m, i) => (
        <mesh key={i} geometry={m.geometry} material={m.material} />
      ))}
    </group>
  )
}

export function Model({ onControlEvent, ...props }: SteamDeckProps) {
  const { nodes, materials } = useGLTF('/models/steam_deck.glb') as unknown as GLTFResult
  const mat = materials['steamDeckIMG.png.001']
  const matShiny = materials['steamDeckIMGShiney.png.001']
  const matEmissive = materials['steamDeckIMGEmissive.png.001']

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* Body */}
        <group position={[0.098, -0.642, 0.485]}>
          <mesh geometry={nodes.body_1.geometry} material={matShiny} />
          <mesh geometry={nodes.body_2.geometry} material={mat} />
          <mesh geometry={nodes.body_3.geometry} material={matEmissive} />
        </group>

        {/* Right joystick — outer collar (ring at gamepad surface) stays fixed.
            Separated in Blender by radial distance > 0.246 (outer = collar, inner = stem). */}
        <RealStick
          control="rightStick"
          tiltMeshes={[
            { geometry: nodes.stick_right_stem_1.geometry, material: matShiny },
            { geometry: nodes.stick_right_stem_2.geometry, material: mat },
          ]}
          fixedMeshes={[
            { geometry: nodes.stick_right_base_1.geometry, material: matShiny },
            { geometry: nodes.stick_right_base_2.geometry, material: mat },
          ]}
          position={[3.038, -1.064, 1.348]}
          onControlEvent={onControlEvent}
        />

        {/* Left joystick */}
        <RealStick
          control="leftStick"
          tiltMeshes={[
            { geometry: nodes.stick_left_stem_1.geometry, material: matShiny },
            { geometry: nodes.stick_left_stem_2.geometry, material: mat },
          ]}
          fixedMeshes={[
            { geometry: nodes.stick_left_base_1.geometry, material: matShiny },
            { geometry: nodes.stick_left_base_2.geometry, material: mat },
          ]}
          position={[-3.038, -1.064, 1.348]}
          onControlEvent={onControlEvent}
        />

        {/* D-pad — real geometry rendered as visual, separate invisible click zone */}
        <mesh geometry={nodes.dpad.geometry} material={mat} position={[-3.444, -0.996, 0.511]} />
        <ClickZone
          control="dpad"
          position={[-3.444, -0.936, 0.511]}
          size={[0.7, 0.15, 0.7]}
          onControlEvent={onControlEvent}
        />

        {/* Button B — real geometry rendered visually, click zone on top */}
        <mesh geometry={nodes.button_b.geometry} material={mat} position={[3.917, -0.936, 0.78]} />
        <ClickZone
          control="b"
          position={[3.917, -0.870, 0.78]}
          size={[0.35, 0.2, 0.35]}
          onControlEvent={onControlEvent}
        />

        {/* Face buttons A / X / Y — visible colored click zones.
            Positions relative to button B at [3.917, -0.936, 0.78]. */}
        <ClickZone
          control="y"
          position={[3.917, -0.870, 0.30]}
          size={[0.35, 0.2, 0.35]}
          color="#E8D23E"
          onControlEvent={onControlEvent}
        />
        <ClickZone
          control="a"
          position={[3.917, -0.870, 1.26]}
          size={[0.35, 0.2, 0.35]}
          color="#3EBF55"
          onControlEvent={onControlEvent}
        />
        <ClickZone
          control="x"
          position={[3.44, -0.870, 0.78]}
          size={[0.35, 0.2, 0.35]}
          color="#3E7BE8"
          onControlEvent={onControlEvent}
        />

        {/* Triggers — real geometry rendered, no click (user said skip) */}
        <group position={[2.509, -0.695, 1.911]}>
          <mesh geometry={nodes.trigger_right_1.geometry} material={matShiny} />
          <mesh geometry={nodes.trigger_right_2.geometry} material={mat} />
        </group>
        <group position={[-2.367, -0.734, 1.937]}>
          <mesh geometry={nodes.trigger_left_1.geometry} material={matShiny} />
          <mesh geometry={nodes.trigger_left_2.geometry} material={mat} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/steam_deck.glb')
